- name: Add ondrej apt key
  apt_key:
    keyserver: 'keyserver.ubuntu.com'
    id: '14AA40EC0831756756D7F66C4F4EA0AAE5267A6C'
    state: 'present'

- name: Install ondrej repo for latest Apache packages
  apt_repository:
    repo: '{{ item }}'
    update_cache: 'yes'
  with_items:
    - 'deb http://ppa.launchpad.net/ondrej/apache2/ubuntu {{ ansible_lsb.codename }} main'
    - 'deb-src http://ppa.launchpad.net/ondrej/apache2/ubuntu {{ ansible_lsb.codename }} main'
